### ISSUE TITLE
How to get an archived release of JDK 17 of Panama or Loom?

### ISSUE THREAD

**Issue by carldea** [oracle-actions/setup-java#13]
Any ideas how to get an archived version of Panama OpenJDK?

I'm trying to get the following archived jdk (Panama for jdk17)
https://jdk.java.net/panama/17/

```
- name: Set up Oracle Open JDK Panama 
      uses: oracle-actions/setup-java@v1
      id: download-jdk
      with:
        website: jdk.java.net
        release: 'panama'
```
This will get the latest.

Thank you,
Carl
