### ISSUE TITLE
[Question] Is cache from `actions/setup-java@v2` supported?

### ISSUE THREAD

**Issue by kkocel** [oracle-actions/setup-java#18]
I wonder if I can leverage the cache mechanism that is provided by `actions/setup-java@v2`?

```yml
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          cache: 'gradle'
```
