### ISSUE TITLE
Expose `actions/setup-java` cache parameter

### ISSUE THREAD

**Issue by scordio** [oracle-actions/setup-java#30]
I would like to use this action as a replacement for some `actions/setup-java` usages we have but then we would lack the [cache settings](https://github.com/actions/setup-java#caching-packages-dependencies) we have today.

Would it be possible to expose the `cache` parameter for the underlying `actions/setup-java`?

The workaround would be to have an explicit `actions/cache` configuration, but using only `oracle-actions/setup-java` would be more elegant.

**Comment by sormuras** [comment]
Hej Stefano,

there's a better way that enables you to make use of **all** inputs supported by the underlying `actions/setup-java` action:

> By default, the `oracle-actions/setup-java` action delegates the actual installation to `actions/setup-java` using its default input value. In order to use customized inputs for `actions/setup-java` step in your workflow run, you may suppress the automatic delegation (`install: false`) and call the installation action with your custom input values.

Copied from: https://github.com/oracle-actions/setup-java/wiki/Customize-setup-java-inputs where a usage example is given.

**Comment by scordio** [comment]
Hi Christian, thanks for the fast feedback!

Right, something like:

```
    steps:
      - name: 'Download Java Development Kit'
        id: download
        uses: oracle-actions/setup-java@v1
        with:
          website: ...
          release: ...
          version: ...
          install: false # Suppress automatic delegation to `actions/setup-java`
      - name: 'Install Java Development Kit'
        uses: actions/setup-java@v2
        with:
          distribution: jdkfile
          jdkFile: ${{ steps.download.outputs.archive }}
          java-version: ${{ steps.download.outputs.version }}
          cache: 'maven'
      - name: ...
```

or the alternative I had in mind:


```
    steps:
      - name: 'Set up Java Development Kit'
        uses: oracle-actions/setup-java@v1
        with:
          website: ...
          release: ...
          version: ...
      - name: 'Cache local Maven repository'
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: ...
```

but I was actually looking for something like:

```
    steps:
      - name: 'Set up Java Development Kit'
        uses: oracle-actions/setup-java@v1
        with:
          website: ...
          release: ...
          version: ...
          cache: 'maven'
      - name: ...
```

Mostly a cosmetic request rather than a functional one 🙂
