### ISSUE TITLE
[feature] Include external JDK code tools through action options

### ISSUE THREAD

**Issue by denismakogon** [oracle-actions/setup-java#31]
As you may know, `jextract` wouldn't be a part of the JDK distro due to its size (and a few other reasons).
I guess `setup-java` should provide options to provide the JDK with `jextract` under the `$JAVA_HOME/bin` path.

**Comment by delabassee** [comment]
FYI, https://jdk.java.net/jextract/ now offers EA `jextract` binaries.

**Comment by sormuras** [comment]
As `jextract` binaries are distributed as a custom runtime image using the default format produced by `jlink`, users may now install `jextract` in their GitHub Actions workflows as follows:

```yml
    - uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net
        release: jextract
```
