### ISSUE TITLE
Add input to override Java version

### ISSUE THREAD

**Issue by sormuras** [oracle-actions/setup-java#34]
Add an input named `install-as-version` to this action enabling an override of the Java version passed to the underlying `actions/setup-java` action.

**Motivation**

The underlying `actions/setup-java` action does NOT allow arbitrary values for its `java-version` input. It uses it to determine the target directory of to where a `jdkFile` is extracted to. It also seems to apply a merging logic when it comes to different releases of the same feature release version number: for example, `19`, `19.0.0`, `19.99.99` and others (including `19.99.99+99-jextract`) are treated as `19` was given.

This prevents installations of multiple releases of JDK N.

**Proposal:**

```yml
  install-as-version:
    description: 'Controls which value is passed as `java-version` to `actions/setup-java`'
    default: PARSE_URI
    required: true
```

Supported values of `install-as-version`:
- `PARSE_URI` [parses](https://github.com/oracle-actions/setup-java/blob/70a68cebaf18bb342845cbfca3ee4a88d2c73313/src/Download.java#L292-L311) the computed or given URI for a valid Java version string
- `HASH_URI` returns the `hashCode()` of the computed or given URI as a string
- All strings supported by `actions/setup-java` as described here: https://github.com/actions/setup-java#supported-version-syntax

This will control/change the output named `version` of this action.

**Comment by sormuras** [comment]
Usage example:

```yml
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: 'Set up jextract'
      uses: oracle-actions/setup-java@issues/34/add-install-as-version-input
      with:
        website: jdk.java.net
        release: jextract
        install-as-version: 123
    
    - name: 'Set up Java 19'
      uses: oracle-actions/setup-java@issues/34/add-install-as-version-input
      with:
        website: jdk.java.net
        release: 19

    - name: 'Print JAVA_HOME and its version information'
      run: |
        echo "JAVA_HOME=$JAVA_HOME"
        java --version
    - name: 'Print help message of jextract'
      run: jextract --help
```
