### ISSUE TITLE
Temporary failure with invalid `java-version` value

### ISSUE THREAD

**Issue by scordio** [oracle-actions/setup-java#39]
Hi team, we experienced [a build failure](https://github.com/assertj/assertj/runs/7723702038) during JDK 18 installation:

```
Error: The string '-457401206' is not valid SemVer notation for a Java version. Please check README file for code snippets and more detailed information
```

It seems that the underlying `actions/setup-java` was invoked with the following parameters:

```
Run actions/setup-java@v3
  with:
    java-version: -457401206
    distribution: jdkfile
    jdkFile: /home/runner/.oracle-actions/setup-java/e4bc9c8a/openjdk-18.0.2_linux-x64_bin.tar.gz
    java-package: jdk
    architecture: x64
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
```

However, the same job executed again [was successful](https://github.com/assertj/assertj/runs/7725378121).
