### ISSUE TITLE
Action fails at aarch64 machine since action.yml hardcodes X64

### ISSUE THREAD

**Issue by vlsi** [oracle-actions/setup-java#63]
See https://github.com/pgjdbc/pgjdbc/actions/runs/6997219349/job/19033952407#step:5:14

Can the action support arm linux as well?
https://github.com/oracle-actions/setup-java/blob/afea155ec9ead9da533a803c03cb135f01e6a949/action.yml#L49

Here's the log (note there's `JAVA_HOME_17_ARM64` environment variable):

```
Run oracle-actions/setup-java@7a0114d66dbd02646abd345c3395b34c148e6126
  with:
    website: jdk.java.net
    release: [2](https://github.com/pgjdbc/pgjdbc/actions/runs/6997140560/job/19033784475#step:5:2)2
    version: latest
    install: true
  env:
    ACTIONS_STEP_DEBUG: true
    ACTIONS_RUNNER_DEBUG: true
    TZ: America/New_York
    JAVA_HOME: /home/pgjdbc/actions-runner/_work/_tool/Java_Oracle_jdk/17/arm64
    JAVA_HOME_17_ARM64: /home/pgjdbc/actions-runner/_work/_tool/Java_Oracle_jdk/17/arm64
Run JAVA=$JAVA_HOME_17_X64/bin/java
  JAVA=$JAVA_HOME_17_X64/bin/java
  DOWNLOAD=$GITHUB_ACTION_PATH/src/Download.java
  if [ ! -z "" ]; then
    $JAVA \
      -Dinstall-as-version="" \
      $DOWNLOAD \
      
  else
    $JAVA \
      -Dinstall-as-version="" \
      $DOWNLOAD \
      jdk.java.net \
      22 \
      latest
  fi
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    ACTIONS_STEP_DEBUG: true
    ACTIONS_RUNNER_DEBUG: true
    TZ: America/New_York
    JAVA_HOME: /home/pgjdbc/actions-runner/_work/_tool/Java_Oracle_jdk/17/arm64
    JAVA_HOME_17_ARM64: /home/pgjdbc/actions-runner/_work/_tool/Java_Oracle_jdk/17/arm64
/home/pgjdbc/actions-runner/_work/_temp/948b854[3](https://github.com/pgjdbc/pgjdbc/actions/runs/6997140560/job/19033784475#step:5:3)-3de5-[4](https://github.com/pgjdbc/pgjdbc/actions/runs/6997140560/job/19033784475#step:5:4)01f-aa19-[6](https://github.com/pgjdbc/pgjdbc/actions/runs/6997140560/job/19033784475#step:5:6)e[9](https://github.com/pgjdbc/pgjdbc/actions/runs/6997140560/job/19033784475#step:5:9)6ade9ce4d.sh: line [10](https://github.com/pgjdbc/pgjdbc/actions/runs/6997140560/job/19033784475#step:5:10): /bin/java: No such file or directory
```

**Comment by vlsi** [comment]
Here's a workaround:

```yaml
      uses: oracle-actions/setup-java@7a0114d66dbd02646abd345c3395b34c148e6126 # v1.3.2
      env:
        # ARM machines miss JAVA_HOME_17_X64, however, the action uses the variable
        JAVA_HOME_17_X64: ${{ env.JAVA_HOME_17_ARM64 || env.JAVA_HOME_17_X64 }}
```
