### ISSUE TITLE
How do you download a specific EA build?

### ISSUE THREAD

**Issue by fbricon** [oracle-actions/setup-java#85]
If you do the following:
```
      - name: Set Up Java
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: EA
```
Then the latest JDK 24 EA build will be downloaded. But I want to use 23 EA. Adding `version: 23` doesn't work.

**Comment by delabassee** [comment]
@fbricon What is your use case to use a specific version of an "older" EA build?

**Comment by fbricon** [comment]
I'm trying to test my build against Java 23. It's not released yet.

**Comment by sormuras** [comment]
See

- #82 

for a more stable variant of an EA build:

```yml
      - name: 'Set up stable EA JDK'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ea
          version: stable
```

Does this help?
