### ISSUE TITLE
Builds using latest and jdk.java.net cannot find JDK for latest release

### ISSUE THREAD

**Issue by mbaumbach** [oracle-actions/setup-java#97]
I believe this is just because the JDK 23 files are no longer available and a new release of this action would fix it by moving to JDK 24. The following error is thrown from the action:

```
Exception in thread "main" java.lang.Error: Could not find URI of JDK[release=23, version=latest, os=linux, arch=x64, type=tar.gz]
```

**Comment by mbaumbach** [comment]
If others are hitting this, if you configure the action with the `uri` property and set it to the appropriate JDK for your system from https://github.com/oracle-actions/setup-java/blob/main/jdk.java.net-uri.properties, it'll work. Example for x64 Linux:

```
- name: Set up JDK
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          uri: https://download.java.net/java/GA/jdk24/1f9ff9062db4449d8ca828c504ffae90/36/GPL/openjdk-24_linux-x64_bin.tar.gz
```
